services:
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./nuxt/DockerFile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt/:/app
      # - ./nuxt/media:/app/media
    env_file: ".env"
    depends_on:
      - db
  db:
    image: postgres
    # restart: unless-stopped
    shm_size: 128mb
    expose:
      - ${NUXT_POSTGRES_PORT}
    ports:
      - "${NUXT_POSTGRES_PORT}:${NUXT_POSTGRES_PORT}"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NUXT_POSTGRES_DB}
      POSTGRES_USER: ${NUXT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${NUXT_POSTGRES_PASSWORD}
  # redis:
  #   image: redis:latest
  #   expose:
  #     - ${NUXT_REDIS_PORT}
  #   ports:
  #     - "${NUXT_REDIS_PORT}:${NUXT_REDIS_PORT}"
  #   command:
  #     - /bin/sh
  #     - -c
  #     - redis-server --requirepass "${NUXT_REDIS_PASSWORD}"
  #   environment:
  #     - REDIS_PASSWORD=${NUXT_REDIS_PASSWORD}
  #     - REDIS_PORT=${NUXT_REDIS_PORT}
  #     - REDIS_DATABASES=16
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - "80:80"
  #   environment:
  #     - NGINX_PORT=80
  #   depends_on:
  #     - nuxt
  #     - db
  #     - redis
  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     - default
  # mail:
  #   image: mailhog/mailhog
  #   expose:
  #     - 8025
  #     - 1025
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
