declare module '@editorjs/header'
declare module '@editorjs/list'
declare module '@editorjs/embed'
declare module '@editorjs/image'
declare module '@editorjs/quote'
declare module '@editorjs/underline'
declare module '@editorjs/checklist'
declare module '@calumk/editorjs-columns'
declare module 'editorjs-drag-drop'
declare module 'editorjs-text-alignment-blocktune'
declare module 'editorjs-text-color-plugin'
declare module 'editorjs-alert'

declare module 'segment-js'